name: flyerapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+5

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  google_sign_in: ^5.3.3
  circular_bottom_navigation: ^2.0.0
  font_awesome_flutter: ^10.1.0
  fluttertoast: ^8.0.9
  firebase_database: ^9.0.15
  country_code_picker: ^2.0.2
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.17
  file_picker: ^4.6.1
  http: ^0.13.4
  modal_progress_hud_nsn: ^0.2.1
  path_provider: ^2.0.11
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  socket_io_client: ^2.0.0
  permission_handler: ^10.0.0
  flutter_pdfview: ^1.2.2
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.8
  flutter_typeahead: ^4.0.0
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  intl: ^0.17.0
  share_plus: ^4.0.10+1
  google_place: ^0.4.7
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  flutter_local_notifications: ^9.9.1
  flutter_facebook_auth: ^4.4.1+1
  flutter_html: ^2.2.1
  passcode_screen: ^2.0.1
  local_auth: ^2.1.2
  mime: ^1.0.2
  url_launcher: ^6.1.6
  the_apple_sign_in: ^1.1.1
  intl_phone_field: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/

  fonts:
    - family: OpenSans-Regular
      fonts:
        - asset: assets/OpenSans/OpenSans-Regular.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: assets/OpenSans/OpenSans-Bold.ttf
    - family: OpenSans-Light
      fonts:
        - asset: assets/OpenSans/OpenSans-Light.ttf
    - family: OpenSans-Medium
      fonts:
        - asset: assets/OpenSans/OpenSans-Medium.ttf
    - family: OpenSans-Semibold
      fonts:
        - asset: assets/OpenSans/OpenSans-SemiBold.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/Roboto/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/Roboto/Roboto-Regular.ttf
    - family: Gothic-Regular
      fonts:
        - asset: assets/Gothic_A1/GothicA1-Regular.ttf
    - family: Gothic-Bold
      fonts:
        - asset: assets/Gothic_A1/GothicA1-Bold.ttf
